### ISSUE TITLE
Importing resource may not work correctly on windows

### ISSUE THREAD

**Issue by orenault** [kangasta/rf-shared-resources#6]
Hi!
We use your library in a python package, in order to bundle some RF keyword libraries that we have developed.
Thanks to your lib, it enables an ease use of our package.

Unfortunatly, its works well on linux, but fails on windows because of the path.

Running on windows (cmd DOS), It appears that the path contains simple \ as separators and this led to an error.
After a quick search, I see that importlib.resources provides a pathlib.path object in the context manager, instead of a purepath. 
(https://docs.python.org/3/library/pathlib.html#pathlib.Path)

Thus, on windows, the path object has only single \, which causes the error (RF need to have double \).

I've done a PR to solve this, just by replacing the \ by /, which is working both on windows or linux.
It may be better to use purepath instead but my fix is enough to fix the issue.
Regards.
O.

**Comment by kangasta** [comment]
Thank you for reporting this and opening a pull request! I'll test the PR and create a new release after merging that to `main`.

**Comment by kangasta** [comment]
Your fix is now available in [v0.1.2](https://pypi.org/project/rf-shared-resources/0.1.2/) ✅
